title: Interactive Chemistry
description: We are a group of student developers making educational games and simulations for Chromebooks, Mac, and Windows devices. We specialize in Chemistry and Physics.
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
  future: true
include:
  - index.md
theme: jekyll-theme-slate
# Google Analytics
google_analytics: G-Y8XTEY4S1B